### ISSUE TITLE
Any ETA yet on App Engine 1.5.0 support?

### ISSUE THREAD

**Issue by drcode** [gcv/appengine-magic#20]
I tried running appengine-magic with the new App Engine 1.5.0 and ran into some problems... I assume this is expected, since appengine-magic still has 1.4.3 as a dependency.

Just curious if there is any timeline for 1.5.0 support yet... I may have some time available around a month from now and will look into submitting some patches if 1.5.0 support is still an open issue at that time. For my current projects I am fine with 1.4.3 for now.

Thanks again for all the great work on appengine-magic!

-Conrad Barski

**Comment by gcv** [comment]
I'll try to make a release with rudimentary 1.5.0 support in the next few days. I don't have time right now to integrate all the nice features (I'm still behind with 1.4.3 on that score), but I'll at least make the 1.5.0 dependencies usable.

**Comment by gcv** [comment]
Did you have trouble with `java.lang.UnsupportedOperationException: enforceApiDeadlines`? If so, it'll take some digging to find out what happened. The stack traces I see suggest that the environment is trying to make asynchronous API calls, and something is configured incorrectly to support deadlines. (The code I'm looking at is in the `v0.4.2` branch.)

**Comment by drcode** [comment]
The problem I encountered seemed to be with form variables the were erroneously null. Sorry I don't have better details, I already rolled back my 1.5.0 environment, since I'm focused on meeting a deadline. However, I will try to submit a patch as needed in June when I will attempt to upgrade again.

**Comment by lhanson** [comment]
I just upgraded my fork of [appengine-clj](https://github.com/lhanson/appengine-clj/) to 1.5.0 and ran into the same `java.lang.UnsupportedOperationException: enforceApiDeadlines` issue. I believe it's caused by a change to `com.google.appengine.tools.development.LocalServerEnvironment`, which the clojure-side proxy doesn't implement. [My fix](https://github.com/lhanson/appengine-clj/commit/762ff8b37c8bf3e92987190b74e9435e972a5c47#src/appengine/environment.clj) might be helpful to take a look at. I believe you might just need to add support for the `enforceApiDeadlines` method to your proxy in `local_env_helpers.clj`.

**Comment by gcv** [comment]
Thank you! That worked.

Everyone interested in 1.5.0: please test the v0.4.2 branch, available in Clojars as `0.4.2-SNAPSHOT`. It works for me. If I don't hear anything in the next few days, I'll release it.

**Comment by gcv** [comment]
App Engine 1.5.1 support is now available in appengine-magic 0.4.2.
