### ISSUE TITLE
Reduce and/or document dependencies

### ISSUE THREAD

**Issue by markokocic** [gcv/appengine-magic#39]
There are a lot of dependencies for appengine-magic. Some are marked as hard dependencies, while might not even be required.

It would be good if next to each dependency it is clearly stated by which services it is needed. 

For example, I want to use only datastore api, and don't care about user/blobstore/memcached. What should I remove from project.clj?
Another examples are jstl, jsp, tomcat ... Am I safe to delete them if I don't want JSP support?
What about commons-*, are they here just for convenience or because ae core is using them?

Also, it would be good if all local repl related dependencies are moved to dev-dependencies.
Do I need those com.google.appengine.\* dependencies in production, or those could be moved to dev-dependencies?

**Comment by gcv** [comment]
I don't add dependencies without an excellent reason. All those which I have added are required for appengine-magic to work as designed. Certainly nothing is added "just for convenience," if by "convenience" you mean "libraries I added because I thought end users might find them handy, but I don't use them myself." Take a look at the comments in appengine-magic's own project.clj file; they give quite a bit of guidance. Remember that Maven has transitive dependency resolution, so some things get pulled in that way.

appengine-magic's dependencies go into `lib/dev/` on your project, so your own project's `lib/` remains as clean as you make it. Production dependencies are copied separately in the appengine-prepare step. Take a look at your `war/WEB-INF/lib/` directory after running this step, and you'll see that not all of Google's dependencies are copied in; in particular, nothing related to JSP goes in. The lancet/copy calls in `appengine_prepare.clj` show the details.

Most of the commons-\* dependencies are used internally. Some are required by App Engine: apps do not deploy without their presence in `war/WEB-INF/lib/`. The JSP dependencies are needed for the `/_ah/admin` interface in interactive REPL mode. If you delete them, it stops working.

You cannot just choose to use the datastore separately from other services. All of App Engine's service interfaces are contained in `appengine-api-1.0-sdk-*.jar` and `appengine-api-labs-*.jar`.

**Comment by markokocic** [comment]
I'm trying to reduce footprint of my application to the bare minimum, in order to reduce warm up time of my application.

For example, servlet-api-2.5 is not needed at runtime, so it shouldn't be added in war/WEB-INF/lib by appengine-prepare
Right now, I manually removed it from war/WEB-INF/lib and successfully deployed the app.
