### ISSUE TITLE
query etc do not appear to return "real" maps

### ISSUE THREAD

**Issue by Folcon** [gcv/appengine-magic#46]
I don't know if this is intended behaviour, but I do find it odd that the maps returned by appengine-magic from the datastore return true to map?, but don't appear to actually be maps. I say this because 

```
(appengine-map :key)
```

Does not appear to work.

It isn't really a problem for me as I do uniformly use (:key {}) style, but I am aware that others don't.

Regards,
Folcon

PS: Please close if this is intended behaviour.

**Comment by gcv** [comment]
Entities retrieved from the datastore are Clojure records, and Clojure records (by design) do not support the `(record :key)` style of accessing a general map.

Maps usually represent one of two different things: objects with well-defined slots, and associative arrays which can have arbitrary keys. In idiomatic Clojure, the first case should use the `(:key obj)` syntax, whereas the second case should use `(obj :key)` or `(get obj :key)`. Records are a high-performance mechanism for the first case, so they only support `(:key record)` for access.

So yes, this is intended behavior.
