### ISSUE TITLE
get the interactive mode running

### ISSUE THREAD

**Issue by komkom** [gcv/appengine-magic#52]
Hey 

Trying to use appengine-magic - looks really interesting

tried to fallow the setup steps closely to set up a development project

at one point in the tutorial they mention that you should compile core.clj, well i am not sure what to do here.
just tried in repl
user=> (compile 'testproj.core) 
nil

after that it should be possible to run the webapp but it does not work.

i executed
user=> (require '[appengine-magic.core :as ae])
user=> (ae/serve testproj-app) 

and this call did not succede.
(ae/serve testproj-app)
java.lang.Exception: Unable to resolve symbol: testproj-app in this context (NO_SOURCE_FILE:7)

at this point i do not now how to proceed. does anyone have any suggestion how to resolve this.

thanks for your help 

best michael

**Comment by gcv** [comment]
The compile form performs ahead-of-time compilation from Clojure source into Java class files. You don't need to do this. You just need to load core.clj. After this, you need to switch to the core namespace and launch the server from there:

```
user=> (load "testproj-app/core")
nil
user=> (in-ns 'testproj-app.core)
#<Namespace testproj-app.core>
cvt1.core=> (ae/serve testproj-app-app)
2011-10-26 09:47:39.491:INFO::Logging to STDERR via org.mortbay.log.StdErrLog
2011-10-26 09:47:39.520:INFO::jetty-6.1.x
...
```

Before doing this, you should delete everything in testproj-app/classes, otherwise anything you precompiled will probably
get in the way.

**Comment by komkom** [comment]
thanks a lot this worked.
best michael
