### ISSUE TITLE
Entites can be retrieved by key, but the key slot is nil

### ISSUE THREAD

**Issue by ghost** [gcv/appengine-magic#7]
When saving new entity, I'm passing nil as a value of the key, and all save! and retrieve works fine, but the key of retrieved entities still contains nil.

(defentity Foo [^:key id, name])
(save! (Foo. nil "Bob"))

(:name (retrieve Foo 1)) ;=> "Bob"
(:id (retrieve Foo 1))       ;=> nil

This behaviour is not local to my system with testing from slime and dev_appserver.sh

Thanks,
Dmitri

**Comment by gcv** [comment]
This is expected behavior, although perhaps it could use better documentation. When you specify a nil primary key for an entity, appengine-magic assumes you want to use automatically generated primary keys. These keys are not stored as user-accessible entity slots. To access them, you need to use the `get-key-object` function. Your call to `retrieve` works because `retrieve` explicitly operates on primary keys, but, as you noted, the `:id` slot is not populated. The `^:key` metadata marker is really just there for cases when you want to specify your own primary keys.

Your example is more idiomatic if you omit the `:id` field altogether: `(defentity Foo [name])`. Incidentally, the production App Engine will not start numbering your objects at 1, and the automatic primary keys will probably not have monotonically increasing numbers.
